### ISSUE TITLE
Answer given to problem right after the problem

### ISSUE THREAD

**Issue by SheepTester** [anematode/gatm#24]
https://github.com/anematode/gatm/blob/0d527814a9a496a68679af474c9c65a8ad5f9a43/map_plane/map_plane_source.tex#L73-L79
I'm not sure if this is intended, but one of the criticisms by our teacher is that an answer to a problem is given right after the problem

**Comment by Nichodon** [comment]
not a bug; its a feature

**Comment by SheepTester** [comment]
Working as intended then
