### ISSUE TITLE
Missing "to"

### ISSUE THREAD

**Issue by SheepTester** [anematode/gatm#25]
**Describe the typo**
https://github.com/anematode/gatm/blob/dfb949dbce6b346d14ef03250257d9a3777f2b9c/mat_gen/mat_gen_source.tex#L19

Pretty sure it's "isomorphic to," so you could do a formal

> Decide to which symmetry group your matrix is isomorphic.

or a more casual and natural

> Decide which symmetry group your matrix is isomorphic to.

**Comment by SheepTester** [comment]
Also, problem 4 has an exclamation mark after 5 that makes it look like a factorial

**Comment by Nichodon** [comment]
Wow, someone actually could say WHAT the typo was. First for everything!

**Comment by Nichodon** [comment]
Thanks for actually saying _what_ the typo was!! 🎉
